### PR TITLE
fix build with qt6

### PR DESCRIPTION
**Pull request by jmlich**

### CODE REVIEW

**Comment by pvuorela** [comment]
There was a rename and work has continue on https://github.com/sailfishos/amber-mpris 

Having already some qt6 fixes.

**Comment by pvuorela** [comment]
Let's close this. Work continues on the amber version.

**Comment by bionade24** [comment]
@pvuorela May you please archive this repo and leave a note then to make it obvious this lib is discontinued?

**Comment by pvuorela** [comment]
cc @keto ^ 

Let's archive this repo.

**Pull request closed without merging**
