### PR TITLE
[qtmpris] Clean up API. Contibutes to JB#53227

### PR DESCRIPTION
**Pull request by inzanity**

### CODE REVIEW

**Comment by pvuorela** [comment]
Thinking if we should avoid the legacy api here. Rationale: the old version needs to be parallel installable and it will then anyhow support old api, do it risk-free and allow not to be installed without need. Only one api here keeps it easier to understand. Apps switching to new api will confirm the real-life use is good too.

Speaking of the parallel installability, we should maybe change all naming, including the package and library names, and eventually create a new repository instead of merging the PR directly.

**Comment by inzanity** [comment]
I now moved the legacy compatibility code to a subdir that is not even built. I guess we could just drop it all though.

And everything is now renamed, and the new repo does sound like a plan, but reviews first, I guess.

**Comment by pvuorela** [comment]
> I now moved the legacy compatibility code to a subdir that is not even built. I guess we could just drop it all though.

+1. Should simplify reviewing the result too.

> And everything is now renamed, and the new repo does sound like a plan, but reviews first, I guess.

We could create the new repo, push current master there and then recreate this PR. I don't think we can merge this here anyway.

**Comment by inzanity** [comment]
> We could create the new repo, push current master there and then recreate this PR. I don't think we can merge this here anyway.

Sure; but before that I'd like to know if anyone objects to the name. :)

**Comment by pvuorela** [comment]
Suppose this can be closed now with the new repository for new api.

**Pull request closed without merging**
